PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
COMMIT;

CREATE TABLE EMPLOYEE (
   EMPLOYEE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME TEXT,
   AGE INTEGER,
   SALARY REAL,
   EMPLOYEE_STATUS TEXT check("EMPLOYEE_STATUS" in ('Availalbe', 'Busy', 'OnCampus', 'OffCampus')),
   RFID_CARD_ID TEXT
);

CREATE TABLE RFID (
    RFID_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RFID_LOCATION TEXT check("RFID_LOCATION" in ('Gate', 'Office', 'Mosque', 'Coffee Shop', 'Rest Room', 'Meeting Room'))
    RFID_STATUS TEXT check("RFID_STATUS" in ('Enter', 'Leave')),
    RFID_CARD_ID TEXT,
    RFID_EMPLOYEE_ID INTEGER,
    FOREIGN KEY(RFID_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);