PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
COMMIT;

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMPLOYEE_NAME TEXT,
    EMPLOYEE_STATUS TEXT check("EMPLOYEE_STATUS" in ('Availalbe', 'Busy', 'OnCampus', 'OffCampus')),
    RFID_CARD_ID TEXT
    LOCATION_ID INTEGER,
    FOREIGN KEY(LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

CREATE TABLE RFIDS (
    RFID_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RFID_LOCATION TEXT check("RFID_LOCATION" in ('Gate', 'Meeting Room', 'Office', 'Mosque', 'Coffee Shop', 'Rest Room'))
    RFID_STATUS TEXT check("RFID_STATUS" in ('Enter', 'Leave')),
    RFID_CARD_ID TEXT,
    RFID_EMPLOYEE_ID INTEGER,
    FOREIGN KEY(RFID_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    LOCATION_ID INTEGER,
    FOREIGN KEY(LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

CREATE TABLE LOCATIONS (
    LOCATION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LOCATION_NAME TEXT UNIQUE,
    RFID_CODE TEXT UNQIUE
);